ResourceIT.Web/Controllers/DetalhesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ResourceIT.Domain;
using ResourceIT.Infra.DataContext;

namespace ResourceIT.Web.Controllers
{
    public class DetalhesController : Controller
    {
        private ResourceITDataContext db = new ResourceITDataContext();

        public ActionResult Index()
        {
            return View(db.Detalhes.ToList());
        }

        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detalhe detalhe = db.Detalhes.Find(id);
            if (detalhe == null)
            {
                return HttpNotFound();
            }
            return View(detalhe);
        }

        public ActionResult Inclusao()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Inclusao([Bind(Include = "Id,Telefone,Endereco")] Detalhe detalhe)
        {
            if (ModelState.IsValid)
            {
                db.Detalhes.Add(detalhe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(detalhe);
        }

        public ActionResult Alteracao(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detalhe detalhe = db.Detalhes.Find(id);
            if (detalhe == null)
            {
                return HttpNotFound();
            }
            return View(detalhe);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Alteracao([Bind(Include = "Id,Telefone,Endereco")] Detalhe detalhe)
        {
            if (ModelState.IsValid)
            {
                db.Entry(detalhe).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(detalhe);
        }

        public ActionResult Exclusao(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Detalhe detalhe = db.Detalhes.Find(id);
            if (detalhe == null)
            {
                return HttpNotFound();
            }
            return View(detalhe);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Exclusao(int id)
        {
            Detalhe detalhe = db.Detalhes.Find(id);
            db.Detalhes.Remove(detalhe);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ResourceIT.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ResourceIT.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ResourceIT.Web/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ResourceIT.Domain;
using ResourceIT.Infra.DataContext;

namespace ResourceIT.Web.Controllers
{
    public class UsuariosController : Controller
    {
        private ResourceITDataContext db = new ResourceITDataContext();
        
        public ActionResult Index()
        {
            var usuarios = db.Usuarios.Include(u => u.Detalhe);
            return View(usuarios.ToList());
        }
        
        public ActionResult Detalhes(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }
        
        public ActionResult Inclusao()
        {
            ViewBag.DetalheId = new SelectList(db.Detalhes, "Id", "Telefone");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Inclusao([Bind(Include = "Id,Nome,Sobrenome,Email,DetalheId")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Usuarios.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DetalheId = new SelectList(db.Detalhes, "Id", "Telefone", usuario.DetalheId);
            return View(usuario);
        }


        public ActionResult Alteracao(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            ViewBag.DetalheId = new SelectList(db.Detalhes, "Id", "Telefone", usuario.DetalheId);
            return View(usuario);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Alteracao([Bind(Include = "Id,Nome,Sobrenome,Email,DetalheId")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DetalheId = new SelectList(db.Detalhes, "Id", "Telefone", usuario.DetalheId);
            return View(usuario);
        }


        public ActionResult Exclusao(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario usuario = db.Usuarios.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Exclusao(int id)
        {
            Usuario usuario = db.Usuarios.Find(id);
            db.Usuarios.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ResourceIT.Web/Views/Detalhes/Alteracao.cshtml
@model ResourceIT.Domain.Detalhe

@{
    ViewBag.Title = "Alteracao";
}

<script>

    function SuccessMessage() {
        swal(
            'Sucesso!',
            'Detalhe alterado com sucesso!',
            'success'
        )
        window.location.href = '/detalhes/index';
    }
    function FailMessage() {
        swal({
            type: 'error',
            title: 'Oops...',
            text: 'Aconteceu algum problema!',
        })
    }
</script>

@using (Ajax.BeginForm("Alteracao", "Detalhes", null, new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "SuccessMessage",
    OnFailure = "FailMessage",
}, new { id = "formAlteracao" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="col-md-10 col-md-offset-1" style="margin-top: 5%; padding-bottom:1.5%; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

        <div style="text-align: center; background-image: linear-gradient(to right, #85d8ed , #0e77a8); padding-top:0%; height:60px;">

            <div style="position: relative; top: 30%">
                <h3>Alteracao Detalhes</h3>
            </div>

        </div>

        <br />

        <div style="text-align: center; background-color: #f2f2f2;">

            <div class="row">
                <div class="col-md-8" style="text-align: left">
                    <strong>Telefone</strong>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12" style="text-align: left">
                    @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="row">
                <div class="col-md-8" style="text-align: left">
                    <strong>Endereco</strong>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12" style="text-align: left">
                    @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="col-md-12" style="text-align: right; padding-right: 0%;">

                <a href="@Url.Action("Index", "Detalhes")" class="btn btn-default" style="background-image: linear-gradient(to right, #85d8ed, #0e77a8); width:150px;">
                    Voltar para lista
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                </a>

                <input type="submit" value="Alterar" class="btn btn-default" style="background-image: linear-gradient(to right, #85d8ed, #0e77a8); width:150px;" />
            </div>

        </div>

    </div>

}

<script src="~/Scripts/mask.js"></script>

<script>
    $('#Telefone').mask('(00) 0000-0000');
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ResourceIT.Web/Views/Detalhes/Detalhes.cshtml
@model ResourceIT.Domain.Detalhe

@{
    ViewBag.Title = "Detalhes";
}


<div class="col-md-10 col-md-offset-1" style="margin-top: 5%; padding-bottom:1.5%; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

    <div style="text-align: center; background-image: linear-gradient(to right, #85d8ed , #0e77a8); padding-top:0%; height:60px;">

        <div style="position: relative; top: 30%">
            <h3>Detalhes do detalhe</h3>
        </div>

    </div>

    <br />

    <div style="text-align: center; background-color: #f2f2f2;">

        <div class="row">
            <div class="col-md-8" style="text-align: left">
                <strong>Telefone</strong>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="text-align: left">
                @Html.DisplayFor(model => model.Telefone)
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-md-8" style="text-align: left">
                <strong>Endereco</strong>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="text-align: left">
                @Html.DisplayFor(model => model.Endereco)
            </div>
        </div>

        <br />

        <div class="col-md-12" style="text-align: right; padding-right: 0%;">

            <a href="@Url.Action("Index", "Detalhes")" class="btn btn-default" style="background-image: linear-gradient(to right, #85d8ed, #0e77a8); width:150px;">
                Voltar para lista
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            </a>

            <a href="@Url.Action("Alteracao", "Detalhes", new { id = Model.Id })" class="btn btn-default" style="background-image: linear-gradient(to right, #85d8ed, #0e77a8); width:150px;">
                Alterar
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </a>

        </div>

    </div>

</div>

ResourceIT.Web/Views/Detalhes/Exclusao.cshtml
@model ResourceIT.Domain.Detalhe


@{
    ViewBag.Title = "Exclusao";
}

<script>
    function SuccessMessage() {
        swal(
            'Sucesso!',
            'Detalhe deletado com sucesso!',
            'success'
        )
        window.location.href = '/detalhes/index';
    }
    function FailMessage() {
        swal({
            type: 'error',
            title: 'Oops...',
            text: 'Aconteceu algum problema!',
        })
    }
</script>

<style>
    input, select, textarea {
        max-width: 1200px;
    }
</style>

<div class="col-md-10 col-md-offset-1" style="margin-top: 5%; padding-bottom:1.5%; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

    <div style="text-align: center; background-image: linear-gradient(to right, #ffb3b3 , #ff3333); padding-top:0%; height:60px;">

        <div style="position: relative; top: 30%">
            <h3>Exclusao Usuario</h3>
        </div>

    </div>

    <h3>Você tem certeza que deseja excluir?</h3>

    <div style="text-align: center; background-color: #f2f2f2;">

        <div class="row">
            <div class="col-md-8" style="text-align: left">
                <strong>Telefone</strong>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="text-align: left">
                @Html.DisplayFor(model => model.Telefone)
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-md-8" style="text-align: left">
                <strong>Endereco</strong>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="text-align: left">
                @Html.DisplayFor(model => model.Endereco)
            </div>
        </div>

        <br />


        @using (Ajax.BeginForm("Delete", "Detalhes", null, new AjaxOptions
        {
            HttpMethod = "POST",
            OnSuccess = "SuccessMessage",
            OnFailure = "FailMessage",
        }, new { id = "formExclusao" }))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="col-md-12" style="text-align: right; padding-right: 0%;">

                <a href="@Url.Action("Index", "Detalhes")" class="btn btn-default" style="background-image: linear-gradient(to right, #85d8ed, #0e77a8); width:150px;">
                    Voltar para lista
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                </a>

                <input type="submit" value="Excluir" class="btn btn-default" style="background-color: #ff3333; width:150px;" />
            </div>
        }

    </div>

</div>

ResourceIT.Web/Views/Detalhes/Inclusao.cshtml
@model ResourceIT.Domain.Detalhe

@{
    ViewBag.Title = "Inclusao";
}

<script>

    function SuccessMessage() {
        swal(
            'Sucesso!',
            'Detalhe cadastrado com sucesso!',
            'success'
        )
        window.location.href = '/detalhes/index';
    }
    function FailMessage() {
        swal({
            type: 'error',
            title: 'Oops...',
            text: 'Aconteceu algum problema!',
        })
    }
</script>

<style>
    input, select, textarea {
        max-width: 1200px;
    }
</style>

@using (Ajax.BeginForm("Inclusao", "Detalhes", null, new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "SuccessMessage",
    OnFailure = "FailMessage",
}, new { id = "formInclusao" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="col-md-10 col-md-offset-1" style="margin-top: 5%; padding-bottom:1.5%; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

        <div style="text-align: center; background-image: linear-gradient(to right, #85d8ed , #0e77a8); padding-top:0%; height:60px;">

            <div style="position: relative; top: 30%">
                <h3>Inclusao Detalhes</h3>
            </div>

        </div>

        <br />

        <div style="text-align: center; background-color: #f2f2f2;">

            <div class="row">
                <div class="col-md-8" style="text-align: left">
                    <strong>Telefone</strong>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12" style="text-align: left">
                    @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="row">
                <div class="col-md-8" style="text-align: left">
                    <strong>Endereco</strong>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12" style="text-align: left">
                    @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="col-md-12" style="text-align: right; padding-right: 0%;">

                <a href="@Url.Action("Index", "Detalhes")" class="btn btn-default" style="background-image: linear-gradient(to right, #85d8ed, #0e77a8); width:150px;">
                    Voltar para lista
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                </a>

                <input type="submit" value="Incluir" class="btn btn-default" style="background-image: linear-gradient(to right, #85d8ed, #0e77a8); width:150px;" />
            </div>

        </div>

    </div>

}

<script src="~/Scripts/mask.js"></script>

<script>
    $('#Telefone').mask('(00) 0000-0000');
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ResourceIT.Web/Views/Detalhes/Index.cshtml
@model IEnumerable<ResourceIT.Domain.Detalhe>

@{
    ViewBag.Title = "Index";
}

<div class="col-md-10 col-md-offset-1" style="margin-top: 5%; padding-bottom:1.5%; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

    <div style="text-align: center; background-image: linear-gradient(to right, #85d8ed , #0e77a8); padding-top:0%; height:60px;">

        <div style="position: relative; top: 30%">
            <h3>Detalhes</h3>
        </div>

    </div>

    <br />

    <div style="text-align:right">
        <a href="@Url.Action("Inclusao", "Detalhes")" class="btn btn-success">
            Inclusao
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
        </a>
    </div>

    <br />

    <div class="row">
        <div class="col-md-4" style="text-align: left">
            <strong>@Html.DisplayNameFor(model => model.Telefone)</strong>
        </div>
        <div class="col-md-4" style="text-align: left">
            <strong>@Html.DisplayNameFor(model => model.Endereco)</strong>
        </div>
    </div>

    <div style="text-align: center; background-color: #f2f2f2;">

        @foreach (var item in Model)
        {
        <div class="row" style="">
            <div class="col-md-4" style="text-align: left;padding-top: 1%;">
                @Html.DisplayFor(modelItem => item.Telefone)
            </div>
            <div class="col-md-4" style="text-align: left; padding-top: 1%;">
                @Html.DisplayFor(modelItem => item.Endereco)
            </div>
            <div class="col-md-4" style="text-align: right">
                <a href="@Url.Action("Detalhes", "Detalhes", new { id = item.Id })" class="btn btn-info">
                    Detalhes
                    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                </a>
                <a href="@Url.Action("Alteracao", "Detalhes", new { id = item.Id })" class="btn btn-info">
                    Alterar
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </a>
                <a href="@Url.Action("Exclusao", "Detalhes", new { id = item.Id })" class="btn btn-info">
                    Excluir
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </a>
            </div>
            <hr />
        </div>
        }


    </div>

</div>

ResourceIT.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ResourceIT.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ResourceIT.Web/Views/Usuarios/Alteracao.cshtml
@model ResourceIT.Domain.Usuario

@{
    ViewBag.Title = "Alteracao";
}

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script>
    function SuccessMessage() {
        swal(
            'Sucesso!',
            'Usuario alterado com sucesso!',
            'success'
        )
        window.location.href = '/usuarios/index';
    }
    function FailMessage() {
        swal({
            type: 'error',
            title: 'Oops...',
            text: 'Aconteceu algum problema!',
        })
    }
</script>

<style>
    input, select, textarea {
        max-width: 1200px;
    }
</style>

@using (Ajax.BeginForm("Alteracao", "Usuarios", null, new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "SuccessMessage",
    OnFailure = "FailMessage",
}, new { id = "formAlteracao" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="col-md-10 col-md-offset-1" style="margin-top: 5%; padding-bottom:1.5%; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

        <div style="text-align: center; background-image: linear-gradient(to right, #85d8ed , #0e77a8); padding-top:0%; height:60px;">

            <div style="position: relative; top: 30%">
                <h3>Alteracao Usuario</h3>
            </div>

        </div>

        <br />

        <div style="text-align: center; background-color: #f2f2f2;">

            <div class="row">
                <div class="col-md-8" style="text-align: left">
                    <strong>Nome</strong>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 " style="text-align: left">
                    @Html.TextBoxFor(model => model.Nome, new { @class = "form-control", style = "width: 100%;" })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="row">
                <div class="col-md-8" style="text-align: left">
                    <strong>Sobrenome</strong>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12" style="text-align: left">
                    @Html.EditorFor(model => model.Sobrenome, new { htmlAttributes = new { @class = "form-control", style = "width: 100%" } })
                    @Html.ValidationMessageFor(model => model.Sobrenome, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="row">
                <div class="col-md-8" style="text-align: left">
                    <strong>Email</strong>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12" style="text-align: left">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", style = "width: 100%" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="row">
                <div class="col-md-8" style="text-align: left">
                    <strong>Telefone</strong>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12" style="text-align: left">
                    @Html.DropDownList("DetalheId", null, htmlAttributes: new { @class = "form-control", style = "width: 100%" })
                    @Html.ValidationMessageFor(model => model.DetalheId, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />

            <div class="col-md-12" style="text-align: right; padding-right: 0%;">

                <a href="@Url.Action("Index", "Usuarios")" class="btn btn-default" style="background-image: linear-gradient(to right, #85d8ed, #0e77a8); width:150px;">
                    Voltar para lista
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                </a>

                <input type="submit" value="Alterar" class="btn btn-default" style="background-image: linear-gradient(to right, #85d8ed, #0e77a8); width:150px;" />
            </div>

        </div>

    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ResourceIT.Web/Views/Usuarios/Detalhes.cshtml
@model ResourceIT.Domain.Usuario

@{
    ViewBag.Title = "Detalhes";
}


<div class="col-md-10 col-md-offset-1" style="margin-top: 5%; padding-bottom:1.5%; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

    <div style="text-align: center; background-image: linear-gradient(to right, #85d8ed , #0e77a8); padding-top:0%; height:60px;">

        <div style="position: relative; top: 30%">
            <h3>Detalhes do usuario</h3>
        </div>

    </div>

    <br />

    <div style="text-align: center; background-color: #f2f2f2;">

        <div class="row">
            <div class="col-md-8" style="text-align: left">
                <strong>@Html.DisplayNameFor(model => model.Nome)</strong>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="text-align: left">
                @Html.DisplayFor(model => model.Nome)
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-md-8" style="text-align: left">
                <strong>@Html.DisplayNameFor(model => model.Sobrenome)</strong>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="text-align: left">
                @Html.DisplayFor(model => model.Sobrenome)
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-md-8" style="text-align: left">
                <strong>@Html.DisplayNameFor(model => model.Email)</strong>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="text-align: left">
                @Html.DisplayFor(model => model.Email)
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-md-8" style="text-align: left">
                <strong>@Html.DisplayNameFor(model => model.Detalhe.Telefone)</strong>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="text-align: left">
                @Html.DisplayFor(model => model.Detalhe.Telefone)
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-md-8" style="text-align: left">
                <strong>@Html.DisplayNameFor(model => model.Detalhe.Endereco)</strong>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="text-align: left">
                @Html.DisplayFor(model => model.Detalhe.Endereco)
            </div>
        </div>

        <br />

        <div class="col-md-12" style="text-align: right; padding-right: 0%;">

            <a href="@Url.Action("Index", "Usuarios")" class="btn btn-default" style="background-image: linear-gradient(to right, #85d8ed, #0e77a8); width:150px;">
                Voltar para lista
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            </a>

            <a href="@Url.Action("Alteracao", "Usuarios", new { id = Model.Id })" class="btn btn-default" style="background-image: linear-gradient(to right, #85d8ed, #0e77a8); width:150px;">
                Alterar
                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </a>

        </div>
    </div>

</div>



<div>
    @Html.ActionLink("Voltar para lista", "Index")
</div>